package com.turnout.ws.repository;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

/**
 * Custom actions have been defined for CustomUiCardsRepository and encapsulates custom retrieval and search behavior with own queries.
 *
 */
@Repository
public class CustomUiCardsRepository {
	
	@Autowired
	protected JdbcTemplate jdbcTemplate; 
	

	/**
	 * Returns list of information that has to showed on stream page like list of studios, new rewards, likes and more.
	 * 
	 * @param ptyid an unique party id.
	 * @param pageno current page number.
	 * @param pagesize total number of records shown in current page.
	 * @return list of stream page information
	 */
	public List getStream(int ptyid, int pageno, int pagesize)
	{
		
		String sql="SELECT STD_ID AS ID,STD_NAME AS NAME,STD_IMAGE_URL AS IMAGE,STD_DESCRIPTION AS DESCRIPTION,STD_LATITUDE AS LATITUDE,STD_LONGITUDE AS LONGITUDE,STD_CREATED_ON AS CREATEDDATE,STD_COMPANY_LOGO AS REL_IMAGE,STUDIO_NAME AS REL_NAME,STD_POINTS AS POINTS,CTYPE ,COMMENTS_CNT,LIKES_CNT,CASE WHEN PTY_LIKED=0 THEN 'NO' ELSE 'YES' END AS PTY_LIKED,JOIN_CNT,PTY_ID,STA_ID,STA_STD_ID,GAINED_TASK_BAGE,STA_START_DATE,STA_END_DATE,STA_EXPIRY_DATE,STA_IMAGE_URL,STA_NAME FROM  ("
			//Normal studios Comes into stream
			+"\n"+ " SELECT S.STD_ID,S.STD_NAME,S.STD_IMAGE_URL,STD_DESCRIPTION,STD_LATITUDE,STD_LONGITUDE,STD_CREATED_ON,STD_COMPANY_LOGO,S.STD_NAME AS STUDIO_NAME,S.STD_POINTS,'STUDIOS' AS CTYPE,"
			+"\n"+ " (SELECT COUNT(*) FROM COMMENTS AS C WHERE C.CMT_TYPE='STUDIOS' AND C.CMT_TYPE_ID=S.STD_ID) AS COMMENTS_CNT,"
			+"\n"+ " (SELECT COUNT(*) FROM LIKES AS L WHERE L.LIKE_YN='Y' AND L.LIKE_TYPE='STUDIOS' AND L.LIKE_TYPE_ID=S.STD_ID) AS LIKES_CNT,"
			+"\n"+ " (SELECT COUNT(*) FROM LIKES AS L WHERE L.LIKE_YN='Y' AND L.LIKE_TYPE='STUDIOS' AND L.LIKE_TYPE_ID=S.STD_ID AND L.LIKE_PTY_ID ="+ptyid+" AND L.LIKE_YN='Y') AS PTY_LIKED,0 AS JOIN_CNT,'' AS PTY_ID,'' AS STA_ID,'' AS STA_STD_ID,'' AS GAINED_TASK_BAGE,'' AS STA_START_DATE,'' AS STA_END_DATE,'' AS STA_EXPIRY_DATE,'' AS STA_IMAGE_URL,'' AS STA_NAME FROM STUDIOS AS S WHERE S.STD_TYPE = 'NORMAL' "
			+"\n"+ "	 UNION"
			//Rewards Comes into stream
			+"\n"+ " SELECT R.RWD_ID,R.RWD_NAME,R.RWD_IMG_URL,R.RWD_DESCRIPTION,0 AS LATITUDE,0 AS LONGITUDE,R.RWD_CREATED_DATE,S.STD_COMPANY_LOGO,S.STD_NAME AS STUDIO_NAME,R.RWD_POINTS,'REWARDS' AS CTYPE,"
			+"\n"+ " (SELECT COUNT(*) FROM COMMENTS AS C WHERE C.CMT_TYPE='REWARDS' AND C.CMT_TYPE_ID=R.RWD_ID) AS COMMENTS_CNT,"
			+"\n"+ " (SELECT COUNT(*) FROM LIKES AS L WHERE L.LIKE_YN='Y' AND L.LIKE_TYPE='REWARDS' AND L.LIKE_TYPE_ID=R.RWD_ID) AS LIKES_CNT,"
			+"\n"+ " (SELECT COUNT(*) FROM LIKES AS L WHERE L.LIKE_YN='Y' AND L.LIKE_TYPE='REWARDS' AND L.LIKE_TYPE_ID=R.RWD_ID AND L.LIKE_PTY_ID ="+ptyid+" AND L.LIKE_YN='Y') AS PTY_LIKED,0 AS JOIN_CNT,'' AS PTY_ID,'' AS STA_ID,'' AS STA_STD_ID,'' AS GAINED_TASK_BAGE,'' AS STA_START_DATE,'' AS STA_END_DATE,'' AS STA_EXPIRY_DATE,'' AS STA_IMAGE_URL,'' AS STA_NAME FROM REWARDS AS R"
			+"\n"+ " LEFT JOIN STUDIOS AS S ON R.RWD_STD_ID=S.STD_ID"
			//Events and Challenges Comes into Stream
			+"\n"+ " UNION "
			+"\n"+ " SELECT SA.STA_ID,SA.STA_NAME,SA.STA_IMAGE_URL,"
			+"\n"+ " CASE WHEN SA.STA_SHORT_DESCRIPTION = '' THEN SA.STA_DESCRIPTION ELSE SA.STA_SHORT_DESCRIPTION END AS DESCRIPTION,SA.STA_LATITUDE,SA.STA_LONGITUDE,SA.STA_CREATED_DATE,S.STD_COMPANY_LOGO,S.STD_NAME AS STUDIO_NAME,"
			+"\n"+ " SA.STA_GOAL_POINTS, CASE WHEN SA.STA_TYPE_ID=1 THEN 'EVENTS' ELSE 'CHALLENGES' END AS CTYPE,(SELECT COUNT(*) FROM COMMENTS AS C WHERE C.CMT_TYPE='STUDIOS_ACTIVITY' AND C.CMT_TYPE_ID=SA.STA_ID) AS COMMENTS_CNT,"
			+"\n"+ " (SELECT COUNT(*) FROM LIKES AS L WHERE L.LIKE_YN='Y' AND L.LIKE_TYPE='STUDIOS_ACTIVITY' AND L.LIKE_TYPE_ID=SA.STA_ID) AS LIKES_CNT,"
			+"\n"+ " (SELECT COUNT(*) FROM LIKES AS L WHERE L.LIKE_YN='Y' AND L.LIKE_TYPE='STUDIOS_ACTIVITY' AND L.LIKE_TYPE_ID=SA.STA_ID AND L.LIKE_PTY_ID ="+ptyid+" AND L.LIKE_YN='Y') AS PTY_LIKED,0 AS JOIN_CNT,'' AS PTY_ID,'' AS STA_ID,'' AS STA_STD_ID,'' AS GAINED_TASK_BAGE,"
			+"\n"+ " SA.STA_START_DATE,SA.STA_END_DATE,SA.STA_EXPIRY_DATE,'' AS STA_IMAGE_URL,'' AS STA_NAME  FROM STUDIOS_ACTIVITY AS SA LEFT JOIN STUDIOS AS S ON SA.STD_ID=S.STD_ID"
			//Checkin Comes into Stream when select Show up preference Public
			+"\n"+ " UNION "
			+"\n"+ " SELECT SPA.PTY_STA_ID,CONCAT(P.PTY_NAME,' ',P.PTY_LAST_NAME) AS PTY_NAME,P.PTY_PHOTO,'' AS DESCRIPTION,CASE WHEN SPA.STA_ID = 0 OR STA_LATITUDE = 0 THEN STD_LATITUDE ELSE STA_LATITUDE END AS LATITUDE,CASE WHEN SPA.STA_ID =0 OR STA_LONGITUDE =0 THEN STD_LONGITUDE ELSE STA_LONGITUDE END AS LONGITUDE,CHECKIN_TIME,STD_COMPANY_LOGO,S.STD_NAME,SPA.GAINED_POINTS,'ATTEND' AS CTYPE,"
			+"\n"+ " (SELECT COUNT(*) FROM COMMENTS AS C WHERE C.CMT_TYPE='STUDIO_PARTY_ACTIVITY' AND C.CMT_TYPE_ID=SPA.PTY_STA_ID) AS COMMENTS_CNT,"
			+"\n"+ " (SELECT COUNT(*) FROM LIKES AS L WHERE L.LIKE_YN='Y' AND L.LIKE_TYPE='STUDIO_PARTY_ACTIVITY' AND L.LIKE_TYPE_ID=SPA.PTY_STA_ID) AS LIKES_CNT,"
			+"\n"+ " (SELECT COUNT(*) FROM LIKES AS L WHERE L.LIKE_YN='Y' AND L.LIKE_TYPE='STUDIO_PARTY_ACTIVITY' AND L.LIKE_TYPE_ID=SPA.PTY_STA_ID AND L.LIKE_PTY_ID ="+ptyid+" AND L.LIKE_YN='Y') AS PTY_LIKED,0 AS JOIN_CNT,SPA.PTY_ID,SPA.STA_ID,STA_STD_ID,'' AS GAINED_TASK_BAGE,'' AS STA_START_DATE,'' AS STA_END_DATE,'' AS STA_EXPIRY_DATE,STA_IMAGE_URL,'' AS STA_NAME FROM STUDIO_PARTY_ACTIVITY AS SPA"
			+"\n"+ " LEFT JOIN PARTY AS P ON SPA.PTY_ID = P.PTY_ID "
			+"\n"+ " LEFT JOIN STUDIOS_ACTIVITY AS SA ON SPA.STA_ID = SA.STA_ID "
			+"\n"+ " LEFT JOIN STUDIOS AS S ON SPA.STA_STD_ID = S.STD_ID WHERE P.PTY_SHOWUP_PREFERENCE='PUBLIC'  AND SPA.PTY_STA_STATUS='ATTEND' AND P.PTY_ID <>"+ptyid
			+"\n"+ " UNION "
			//Checkin Comes into Stream when select Show up preference Follower
			+"\n"+ " SELECT SPA.PTY_STA_ID,CONCAT(P.PTY_NAME,' ',P.PTY_LAST_NAME) AS PTY_NAME,P.PTY_PHOTO,'' AS DESCRIPTION,CASE WHEN SPA.STA_ID = 0 OR STA_LATITUDE = 0 THEN STD_LATITUDE ELSE STA_LATITUDE END AS LATITUDE,CASE WHEN SPA.STA_ID = 0 OR STA_LONGITUDE=0 THEN STD_LONGITUDE ELSE STA_LONGITUDE END AS LONGITUDE,CHECKIN_TIME,STD_COMPANY_LOGO,S.STD_NAME,SPA.GAINED_POINTS,'ATTEND' AS CTYPE,"
			+"\n"+ " (SELECT COUNT(*) FROM COMMENTS AS C WHERE C.CMT_TYPE='STUDIO_PARTY_ACTIVITY' AND C.CMT_TYPE_ID=SPA.PTY_STA_ID) AS COMMENTS_CNT,"
			+"\n"+ " (SELECT COUNT(*) FROM LIKES AS L WHERE L.LIKE_YN='Y' AND L.LIKE_TYPE='STUDIO_PARTY_ACTIVITY' AND L.LIKE_TYPE_ID=SPA.PTY_STA_ID) AS LIKES_CNT,"
			+"\n"+ " (SELECT COUNT(*) FROM LIKES AS L WHERE L.LIKE_YN='Y' AND L.LIKE_TYPE='STUDIO_PARTY_ACTIVITY' AND L.LIKE_TYPE_ID=SPA.PTY_STA_ID AND L.LIKE_PTY_ID ="+ptyid+" AND L.LIKE_YN='Y') AS PTY_LIKED,0 AS JOIN_CNT,SPA.PTY_ID,SPA.STA_ID,STA_STD_ID,'' AS GAINED_TASK_BAGE,'' AS STA_START_DATE,'' AS STA_END_DATE,'' AS STA_EXPIRY_DATE,STA_IMAGE_URL,'' AS STA_NAME FROM STUDIO_PARTY_ACTIVITY AS SPA"
			+"\n"+ " LEFT JOIN PARTY AS P ON SPA.PTY_ID = P.PTY_ID"
			+"\n"+ " LEFT JOIN STUDIOS_ACTIVITY AS SA ON SPA.STA_ID = SA.STA_ID "
			+"\n"+ " LEFT JOIN STUDIOS AS S ON SPA.STA_STD_ID = S.STD_ID WHERE P.PTY_ID IN (SELECT FRND_ID2 FROM FRIENDS WHERE FRND_ID1 ="+ptyid+" AND FRND_STATUS='FOLLOW'"
			+"\n"+ " UNION "
			+"\n"+ " SELECT FRND_ID1 FROM FRIENDS WHERE FRND_ID2 = "+ptyid+" AND FRND_STATUS='FOLLOW') AND P.PTY_SHOWUP_PREFERENCE='FOLLOWER' AND SPA.PTY_STA_STATUS='ATTEND' AND P.PTY_ID <>"+ptyid
			+"\n"+ "  UNION "
			//Checkin Comes into Stream when select Show up preference OnlyMe
			+"\n"+ " SELECT SPA.PTY_STA_ID,CONCAT(P.PTY_NAME,' ',P.PTY_LAST_NAME) AS PTY_NAME,P.PTY_PHOTO,'' AS DESCRIPTION,CASE WHEN STA_LATITUDE=0 THEN STD_LATITUDE ELSE STA_LATITUDE END AS LATITUDE,CASE WHEN STA_LONGITUDE=0 THEN STD_LONGITUDE ELSE STA_LONGITUDE END AS LONGITUDE,CHECKIN_TIME,STD_COMPANY_LOGO,S.STD_NAME,SPA.GAINED_POINTS,'ATTEND' AS CTYPE,"
			+"\n"+ " (SELECT COUNT(*) FROM COMMENTS AS C WHERE C.CMT_TYPE='STUDIO_PARTY_ACTIVITY' AND C.CMT_TYPE_ID=SPA.PTY_STA_ID) AS COMMENTS_CNT,"
			+"\n"+ " (SELECT COUNT(*) FROM LIKES AS L WHERE L.LIKE_YN='Y' AND L.LIKE_TYPE='STUDIO_PARTY_ACTIVITY' AND L.LIKE_TYPE_ID=SPA.PTY_STA_ID) AS LIKES_CNT,"
			+"\n"+ " (SELECT COUNT(*) FROM LIKES AS L WHERE L.LIKE_YN='Y' AND L.LIKE_TYPE='STUDIO_PARTY_ACTIVITY' AND L.LIKE_TYPE_ID=SPA.PTY_STA_ID AND L.LIKE_PTY_ID ="+ptyid+" AND L.LIKE_YN='Y') AS PTY_LIKED,0 AS JOIN_CNT,SPA.PTY_ID,SPA.STA_ID,STA_STD_ID,'' AS GAINED_TASK_BAGE,'' AS STA_START_DATE,'' AS STA_END_DATE,'' AS STA_EXPIRY_DATE,STA_IMAGE_URL,'' AS STA_NAME FROM STUDIO_PARTY_ACTIVITY AS SPA"
			+"\n"+ " LEFT JOIN PARTY AS P ON SPA.PTY_ID = P.PTY_ID "
			+"\n"+ " LEFT JOIN STUDIOS_ACTIVITY AS SA ON SPA.STA_ID = SA.STA_ID "
			+"\n"+ " LEFT JOIN STUDIOS AS S ON SPA.STA_STD_ID = S.STD_ID WHERE P.PTY_ID ="+ptyid+" AND P.PTY_SHOWUP_PREFERENCE='ONLYME'   AND SPA.PTY_STA_STATUS='ATTEND'"
			+"\n"+ "  UNION "
			//Interested,Accepted Comes into Stream when select Activity preference Public
			+"\n"+ " SELECT SPA.PTY_STA_ID,CONCAT(P.PTY_NAME,' ',P.PTY_LAST_NAME) AS PTY_NAME,P.PTY_PHOTO,SA.STA_SHORT_DESCRIPTION,CASE WHEN STA_LATITUDE=0 THEN STD_LATITUDE ELSE STA_LATITUDE END AS LATITUDE,CASE WHEN STA_LONGITUDE=0 THEN STD_LONGITUDE ELSE STA_LONGITUDE END AS LONGITUDE,CHECKIN_TIME,STD_COMPANY_LOGO,S.STD_NAME,SPA.GAINED_POINTS,SPA.PTY_STA_STATUS AS CTYPE,"
			+"\n"+ " (SELECT COUNT(*) FROM COMMENTS AS C WHERE C.CMT_TYPE='STUDIO_PARTY_ACTIVITY' AND C.CMT_TYPE_ID=SPA.PTY_STA_ID) AS COMMENTS_CNT,"
			+"\n"+ " (SELECT COUNT(*) FROM LIKES AS L WHERE L.LIKE_YN='Y' AND L.LIKE_TYPE='STUDIO_PARTY_ACTIVITY' AND L.LIKE_TYPE_ID=SPA.PTY_STA_ID) AS LIKES_CNT,"
			+"\n"+ " (SELECT COUNT(*) FROM LIKES AS L WHERE L.LIKE_YN='Y' AND L.LIKE_TYPE='STUDIO_PARTY_ACTIVITY' AND L.LIKE_TYPE_ID=SPA.PTY_STA_ID AND L.LIKE_PTY_ID ="+ptyid+" AND L.LIKE_YN='Y') AS PTY_LIKED,"
			+"\n"+ " (SELECT COUNT(*) FROM STUDIO_PARTY_ACTIVITY AS ISPA WHERE ISPA.PTY_STA_STATUS <> 'ATTEND' AND ISPA.PTY_STA_STATUS <> 'WONBADGE'  AND ISPA.STA_ID=SPA.STA_ID AND ISPA.PTY_ID <> SPA.PTY_ID) AS JOIN_CNT,SPA.PTY_ID,SPA.STA_ID,STA_STD_ID,SPA.GAINED_TASK_BAGE,'' AS STA_START_DATE,SA.STA_END_DATE,SA.STA_EXPIRY_DATE,STA_IMAGE_URL,SA.STA_NAME  FROM STUDIO_PARTY_ACTIVITY AS SPA"
			+"\n"+ " LEFT JOIN STUDIOS_ACTIVITY AS SA ON SPA.STA_ID = SA.STA_ID "
			+"\n"+ " LEFT JOIN PARTY AS P ON SPA.PTY_ID = P.PTY_ID"
			+"\n"+ " LEFT JOIN STUDIOS AS S ON SPA.STA_STD_ID = S.STD_ID WHERE P.PTY_ACTIVITY_PREFERENCE='PUBLIC'  AND SPA.PTY_STA_STATUS <> 'ATTEND' AND P.PTY_ID <>"+ptyid
			+"\n"+ " UNION "
			//Interested,Accepted Comes into Stream when select Activity preference Follower
			+"\n"+ " SELECT SPA.PTY_STA_ID,CONCAT(P.PTY_NAME,' ',P.PTY_LAST_NAME) AS PTY_NAME,P.PTY_PHOTO,SA.STA_SHORT_DESCRIPTION,CASE WHEN STA_LATITUDE=0 THEN STD_LATITUDE ELSE STA_LATITUDE END AS LATITUDE,CASE WHEN STA_LONGITUDE=0 THEN STD_LONGITUDE ELSE STA_LONGITUDE END AS LONGITUDE,CHECKIN_TIME,STD_COMPANY_LOGO,S.STD_NAME,SPA.GAINED_POINTS,SPA.PTY_STA_STATUS AS CTYPE,"
			+"\n"+ " (SELECT COUNT(*) FROM COMMENTS AS C WHERE C.CMT_TYPE='STUDIO_PARTY_ACTIVITY' AND C.CMT_TYPE_ID=SPA.PTY_STA_ID) AS COMMENTS_CNT,"
			+"\n"+ " (SELECT COUNT(*) FROM LIKES AS L WHERE L.LIKE_YN='Y' AND L.LIKE_TYPE='STUDIO_PARTY_ACTIVITY' AND L.LIKE_TYPE_ID=SPA.PTY_STA_ID) AS LIKES_CNT,"
			+"\n"+ " (SELECT COUNT(*) FROM LIKES AS L WHERE L.LIKE_YN='Y' AND L.LIKE_TYPE='STUDIO_PARTY_ACTIVITY' AND L.LIKE_TYPE_ID=SPA.PTY_STA_ID AND L.LIKE_PTY_ID ="+ptyid+" AND L.LIKE_YN='Y') AS PTY_LIKED,"
			+"\n"+ " (SELECT COUNT(*) FROM STUDIO_PARTY_ACTIVITY AS ISPA WHERE ISPA.PTY_STA_STATUS <> 'ATTEND' AND ISPA.PTY_STA_STATUS <> 'WONBADGE'  AND ISPA.STA_ID=SPA.STA_ID AND ISPA.PTY_ID <> SPA.PTY_ID) AS JOIN_CNT,SPA.PTY_ID,SPA.STA_ID,STA_STD_ID,SPA.GAINED_TASK_BAGE,'' AS STA_START_DATE,SA.STA_END_DATE,SA.STA_EXPIRY_DATE,STA_IMAGE_URL,SA.STA_NAME  FROM STUDIO_PARTY_ACTIVITY AS SPA"
			+"\n"+ " LEFT JOIN STUDIOS_ACTIVITY AS SA ON SPA.STA_ID = SA.STA_ID "
			+"\n"+ " LEFT JOIN PARTY AS P ON SPA.PTY_ID = P.PTY_ID "
			+"\n"+ " LEFT JOIN STUDIOS AS S ON SPA.STA_STD_ID = S.STD_ID WHERE P.PTY_ID IN (SELECT FRND_ID2 FROM FRIENDS WHERE FRND_ID1 ="+ptyid+" AND FRND_STATUS='FOLLOW'"
			+"\n"+ " UNION "
			+"\n"+ " SELECT FRND_ID1 FROM FRIENDS WHERE FRND_ID2 = "+ptyid+" AND FRND_STATUS='FOLLOW') AND P.PTY_ACTIVITY_PREFERENCE='FOLLOWER' AND SPA.PTY_STA_STATUS <> 'ATTEND'   AND P.PTY_ID <>"+ptyid
			+"\n"+ " UNION "
			//Added Friends Comes into Stream
			+"\n"+ " SELECT FRND_ID1,CONCAT(P1.PTY_NAME,' ',P1.PTY_LAST_NAME) AS PTY_NAME,P1.PTY_PHOTO,'' AS STA_NAME,'' AS STD_LATITUDE,'' AS STD_LONGITUDE,FRND_MODIFY_DATE,P2.PTY_PHOTO,CONCAT(P2.PTY_NAME,' ',P2.PTY_LAST_NAME) AS PTY_NAME,0 AS GAINED_POINTS,'FRIENDS' AS CTYPE,"
			+"\n"+ " (SELECT COUNT(*) FROM COMMENTS AS C WHERE C.CMT_TYPE='FRIENDS' AND C.CMT_TYPE_ID=FRND_ID1) AS COMMENTS_CNT,"
			+"\n"+ " (SELECT COUNT(*) FROM LIKES AS L WHERE L.LIKE_YN='Y' AND L.LIKE_TYPE='FRIENDS' AND L.LIKE_TYPE_ID=FRND_ID1) AS LIKES_CNT,"
			+"\n"+ " (SELECT COUNT(*) FROM LIKES AS L WHERE L.LIKE_YN='Y' AND L.LIKE_TYPE='FRIENDS' AND L.LIKE_TYPE_ID=FRND_ID1 AND L.LIKE_PTY_ID ="+ptyid+" AND L.LIKE_YN='Y') AS PTY_LIKED,0 AS JOIN_CNT,FRND_ID2 AS PTY_ID,'' AS STA_ID,'' AS STA_STD_ID,'' AS GAINED_TASK_BAGE,'' AS STA_START_DATE,'' AS STA_END_DATE,'' AS STA_EXPIRY_DATE,'' AS STA_IMAGE_URL,'' AS STA_NAME"
			+"\n"+ "  FROM FRIENDS AS F "
			+"\n"+ " LEFT JOIN PARTY AS P1 ON F.FRND_ID2 = P1.PTY_ID "
			+"\n"+ " LEFT JOIN PARTY AS P2 ON F.FRND_ID1 = P2.PTY_ID "
			+"\n"+ " WHERE FRND_STATUS='FOLLOW' "
			+"\n"+ "  UNION "
			//Reedem a Reward Comes into Stream
			+"\n"+ " SELECT VP.VOC_ID,CONCAT(P.PTY_NAME,' ',P.PTY_LAST_NAME) AS PTY_NAME,P.PTY_PHOTO,RWD_NAME,'' AS LATITUDE,'' AS LONGITUDE,VOC_STATUS_DATE AS CREATEDDATE,STD_COMPANY_LOGO AS REL_IMAGE,"
			+"\n"+ " STD_NAME AS REL_NAME,VOC_REEDEMED_POINTS AS POINTS,'REEDEM' AS CTYPE,(SELECT COUNT(*) FROM COMMENTS AS C WHERE C.CMT_TYPE='VOUCHER_PARTY' AND C.CMT_TYPE_ID=VP.VOC_ID) AS COMMENTS_CNT,"
			+"\n"+ " (SELECT COUNT(*) FROM LIKES AS L WHERE L.LIKE_YN='Y' AND L.LIKE_TYPE='VOUCHER_PARTY' AND L.LIKE_TYPE_ID=VP.VOC_ID) AS LIKES_CNT,"
			+"\n"+ " (SELECT COUNT(*) FROM LIKES AS L WHERE L.LIKE_YN='Y' AND L.LIKE_TYPE='VOUCHER_PARTY' AND L.LIKE_TYPE_ID=VP.VOC_ID AND L.LIKE_PTY_ID ="+ptyid+" AND L.LIKE_YN='Y') AS PTY_LIKED,0 AS JOIN_CNT,P.PTY_ID AS PTY_ID,RWD_ID AS STA_ID,RWD_STD_ID AS STA_STD_ID,'' AS GAINED_TASK_BAGE,'' AS STA_START_DATE,"
			+"\n"+ " '' AS STA_END_DATE,'' AS STA_EXPIRY_DATE,RWD_IMG_URL AS STA_IMAGE_URL,'' AS STA_NAME  FROM VOUCHER_PARTY AS VP "
			+"\n"+ " LEFT JOIN  REWARDS_HAS_VOUCHER  AS RHV ON VP.VOC_ID = RHV.VOC_VOC_ID "
			+"\n"+ " LEFT JOIN REWARDS AS R ON RHV.RWD_RWD_ID = R.RWD_ID "
			+"\n"+ " LEFT JOIN STUDIOS AS S ON R.RWD_STD_ID = S.STD_ID "
			+"\n"+ " LEFT JOIN PARTY AS P ON VP.PTY_ID = P.PTY_ID "
			+"\n"+ "  UNION "
			//Instagram Comes into Stream
			+"\n"+ " SELECT IN_POST_ID,IN_POST_TYPE,IN_POST_DATA_PATH,IN_POST_DATA_LINK,'' AS STD_LATITUDE,'' AS STD_LONGITUDE,IN_POST_CRTIME,IN_POST_USR_PIC,IN_POST_USR_FULLNAME,0 AS GAINED_POINTS,'INSTAGRAM' AS CTYPE,"
			+"\n"+ " IN_POST_CMT_CNT,IN_POST_LIKES_CNT,0 AS PTY_LIKED,0 AS JOIN_CNT,'' AS PTY_ID,'' AS STA_ID,'' AS STA_STD_ID,'' AS GAINED_TASK_BAGE,'' AS STA_START_DATE,'' AS STA_END_DATE,'' AS STA_EXPIRY_DATE,'' AS STA_IMAGE_URL,'' AS STA_NAME "
			+"\n"+ " FROM FITERNITY_POST ) AS X "
			+"\n"+ " ORDER BY STD_CREATED_ON DESC LIMIT "+pageno+","+pagesize ;
			
			System.out.println("STREAM QUERY <======>"+sql);
			return jdbcTemplate.queryForList(sql);						
	}
	
	/**
	 * Returns list of premium studios.
	 * 
	 * @param ptyid an unique party id.
	 * @return List of premium studio.
	 */
	public List getPremiumStudio(int ptyid)
	{
		String sql= " SELECT S.STD_ID AS ID,S.STD_NAME AS NAME,S.STD_IMAGE_URL AS IMAGE,STD_STREAM_DESC AS DESCRIPTION,STD_LATITUDE AS LATITUDE,STD_LONGITUDE AS LONGITUDE,STD_CREATED_ON AS CREATEDDATE,STD_COMPANY_LOGO AS REL_IMG,S.STD_NAME AS REL_NAME,S.STD_POINTS AS POINTS,'STUDIOS' AS CTYPE,"
				+ " (SELECT COUNT(*) FROM COMMENTS AS C WHERE C.CMT_TYPE='STUDIOS' AND C.CMT_TYPE_ID=S.STD_ID) AS COMMENTS_CNT,"
				+ " (SELECT COUNT(*) FROM LIKES AS L WHERE L.LIKE_YN='Y' AND L.LIKE_TYPE='STUDIOS' AND L.LIKE_TYPE_ID=S.STD_ID) AS LIKES_CNT,"
				+"\n"+ " (SELECT COUNT(*) FROM LIKES AS L WHERE L.LIKE_YN='Y' AND L.LIKE_TYPE='STUDIOS' AND L.LIKE_TYPE_ID=S.STD_ID AND L.LIKE_PTY_ID ="+ptyid+") AS PTY_LIKED,'' AS PTY_ID,'' AS STA_ID,'' AS STA_STD_ID,'' AS GAINED_TASK_BAGE,'' AS STA_START_DATE,'' AS STA_END_DATE,'' AS STA_EXPIRY_DATE FROM STUDIOS AS S WHERE S.STD_TYPE='PREMIUM' ORDER BY STD_CREATED_ON" ;
		return jdbcTemplate.queryForList(sql);
	}

}
